config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'dashboard' => 'dashboard#show', as: :dashboard
  get 'dashboard/:filter' => 'dashboard#show'
  get 'search' => 'search#index'
  
  authenticate :user do
     get "posts/:id/connect" => 'posts#connect', as: :post_connect
     delete "posts/:id" => 'posts#destroy', as: :destroy_post
     get "profiles/:id" => 'profiles#show', as: :profile
     resources :posts, only: [:new, :create, :edit, :update, :destroy, :show] do
     	resources :reviews, only: [:new, :create, :edit, :update, :destroy]
     end
     resources :users, only: [:show, :index, :edit, :destroy, :update]
   end
  get 'home' => 'home#index', as: :after_sign_out_path_for
  root 'home#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  searchkick autocomplete: ['name']

  has_and_belongs_to_many :tags

  belongs_to :user
  belongs_to :buyer, class_name: 'User'
  belongs_to :created_by, class_name: 'User'
  has_many :reviews

  enum status: {
    open: 0,
    completed: 1,
    old: 2
  }

  validates :title,         presence: true

  validates :description,   presence: true


  attr_reader :tag_tokens, :give
  attr_accessible :title, :description, :user, :tag_tokens

  def tag_tokens=(tokens)
    self.tag_ids = Tag.ids_from_tokens(tokens)
  end

  def give=(val)
    if val == true
      self.user = current_user
    else
      self.buyer = current_user
    end
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  belongs_to :reviewee, class_name: 'User'


  validates :user_id,  presence: true
  validates :reviewee_id,  presence: true
  validates :post_id,  presence: true
  validates :score,  presence: true
  validates :feedback,  presence: true,
                        length: { in: 3..256 }
  validates :title,  presence: true,length: { in: 3..128 }

  #enum score: {
  #  neutral: 0,
  #  negative: -1,
  #  positive: 1
  #}
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  searchkick autocomplete: ['name']

  has_and_belongs_to_many :posts

  validates :name,  presence: true,
                    uniqueness: true,
                    length: { in: 1..25 }

  attr_accessible :name

  def self.tokens(query)
    tags = where("name like ?", "%#{query}%")
    if tags.empty?
      [{id: "<<<#{query}>>>", name: "New: \"#{query}\""}]
    else
      tags
    end
  end

  def self.ids_from_tokens(tokens)
    tokens.gsub!(/<<<(.+?)>>>/) { create!(name: $1).id }
    tokens.split(',')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: {
    person: 0,
    organization: 1,
    admin: 2
  }

  has_many :posts
  has_many :reviews

  validates :name,  presence: true


  attr_accessible :name, :email, :password


  def can_post
    if self.completed_transactions.last
      if self.completed_transactions.last.reviews.count > 0
        if self.completed_transactions.last.reviews.where(buyer: self)
          true
        else
          false
        end
      else
        false
      end
    else
      true
    end
  end

  def completed_posts
    self.posts.completed
  end

  def completed_transactions
    Post.where(buyer: self).completed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout false

  def show
    if params[:filter] == "open"
      @posts = Post.where(created_by: current_user).open.order('created_at DESC')
      #@posts = current_user.posts.open
      #@posts.zip(Post.where(buyer: current_user).open).flatten.compact
   elsif params[:filter] == "completed"
      #@posts = current_user.posts.completed
      @posts = Post.where(created_by: current_user).completed.order('created_at DESC')
      @posts = @posts + Post.where(buyer_id: current_user).completed 
   #@posts.zip(Post.where(buyer: current_user).completed).flatten.compact
    elsif params[:filter] == "all"
      @posts = Post.where(created_by: current_user).order('created_at DESC')
      #@posts.zip(Post.where(created_by: current_user)).flatten.compact
    else
      @posts = Post.all.order('created_at DESC')
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout false

  def index
  	if user_signed_in?
      redirect_to dashboard_path
  	end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :html, :js

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(params[:post])
    @post.created_by = current_user

    if params[:post]['give']
      @post.user = current_user
    else
      @post.buyer = current_user
    end

    @post.save

    respond_with @post
  end

  def update
    @post = Post.find(params[:id])
    @post.update_attributes(params[:post])

    respond_with @post
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to dashboard_path
  end

  def connect
    @post = Post.find(params[:id])

    if @post.user
      @post.buyer = current_user
    else
      @post.user = current_user
    end

    @post.status = :completed

    @post.save

    redirect_to dashboard_path
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	layout false

  def show
    @user = User.find(params[:id])
    @posts = Post.where(created_by: @user)
    @reviews = Review.where(reviewee: @user)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authenticate_user!, except: [:index]
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_post, except: [:index]

  def index
    @review = Review.all
  end

  def show
  end

  def new
    @page_title = 'Add Review'
    @review = Review.new
  end

  def edit
  end

  def create
    @review = current_user.reviews.build(review_params)
    if @post.user_id != current_user.id
      @review.reviewee_id = @post.user_id
    else
      @review.reviewee_id = @post.buyer_id
    end
    if @review.save
        flash[:notice] = "Review Created"
        redirect_to root_path
    else
        flash[:alert] = "Review Not Created"
        render 'new'
    end
  end

  def update
    if @review.update(review_params)
          flash[:notice] = "Review Updated"
          redirect_to :action => 'show', :id => @review
    else
          flash[:alert] = "Review Not Updated"
          render :action => 'edit'
    end
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def review_params
      params.require(:review).permit(:title, :feedback, :score, :post_id, :reviewee_id).merge(post_id: @post.id)
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  layout false

  def index
    if params[:query].present?
      @results = Array.new

      @posts = Post.search params[:query], partial: true
      @tags = Tag.search params[:query], partial: true

      @posts.each do |post|
        @results << post
      end

      add = true
      @tags.each do |tag|
        tag.posts.each do |tag_loc|
          @results.each do |loc|
            add = false if loc.name == tag_loc.name
          end
          @results << tag_loc if add
          add = true
        end
      end
    else
      @results = Post.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def get_gravatar(user,size=150)
    unless user.nil?
  	 "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}.jpg?s=#{size}"
    end
	end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/dashboard/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Karmik</title>
	<%= stylesheet_link_tag 'dashboard.css' %>
	<%= stylesheet_link_tag 'button.css' %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
	<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"/>
	<link href='http://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700,300italic' rel='stylesheet' type='text/css'>

</head>
<body>
	<div class="headerWrapper">
		<div class="header">
			<%= link_to dashboard_path do %>
				<%= image_tag 'karmic-logo.svg', class: 'logo' %>
			<% end %>
			<div class="navLinks">
				<%= link_to search_path, class: 'navLink' do%>
					<div>Search</div>
				<% end %>
				<%= link_to profile_path(current_user), class: 'navLink' do %>
					<div><%= current_user.name %></div>
				<% end %>
				<% if user_signed_in? %>
					<%= link_to destroy_user_session_path, method: :delete, class: 'navLink' do %>
						<div>Sign Out</div>
					<% end %>
				<% end %>
				<div class="navLink">
					<script src="https://checkout.stripe.com/checkout.js"></script>
					<button id="customButton">Go Premium</button>
					<script>
					var handler = StripeCheckout.configure({
						key: 'pk_test_VA8Gg7GG9kMwVekeBFtgrPNC',
						image: '/assets/k-icon.jpg',
						token: function(token, args) {
							// Use the token to create the charge with a server-side script.
						}
					});

					document.getElementById('customButton').addEventListener('click', function(e) {
						// Open Checkout with further options
						handler.open({
							name: 'Karmik',
							description: 'Activate Premium',
							amount: 500
						});
						e.preventDefault();
					});
					</script>
				</form>
			</div>
	  </div>
	</div>
</div>
<div class="heroWrapper">
	<div class="hero">
		<h1>Dashboard</h1>
	</div>
	</div>
<div class="dashboardWrapper">
	<div class="feedWrapper">
		<div class="feedBox">
			<div class="postFeed">
				<% if @posts.empty? %>
					<h2 class="feedHead"><i>No posts found. :'( </i></h2>
				<% else %>
					<h2 class="feedHead">Recent Posts in Your Community</h2>
					<% @posts.each do |post| %>
						<div class="post <%= post.created_by == post.user ? 'takePost' : 'givePost' %>">
							<img src=<%= get_gravatar(post.created_by)%> class="feedProfilePic"/>
							<div class="feedTextBox">
								<h3 class="postTitle"><%= post.title %></h3>
								<p><%= post.description %></p>
								<%= link_to post_path post do %>
									<%= link_to post_connect_path post do %><div class="postButton">Connect</div><% end %>
									<%= link_to profile_path(post.created_by) do %><div class="viewButton2">View Profile</div><% end %>
									<% if post.created_by == current_user %>
										<%= link_to edit_post_path post do %><div class="viewButton3">Edit</div><% end %>
									 <%= link_to 'Delete',destroy_post_path(post), class: 'viewButton4', method: :delete, data: { confirm: "Are you sure?" } %></td>
						      	<%= link_to new_post_review_path post do %><div class="viewButton4">Review</div><% end %>
									<% elsif post.buyer == current_user %>
										 <%= link_to new_post_review_path post do %><div class="viewButton4">Review</div><% end %>
								  <% end %>
							  <% end %>
		 					</div>
	 				  </div>
	 			  <% end %>
	 		  <% end %>
	 		</div>
	 	</div>
	</div>
	<div class="sidebarWrapper">
		<div class="sidebar">
			<h1>Welcome <%= current_user.name %>!</h1>
			<ul>
				<%= link_to new_post_path do%>
					<li>New Post</li>
				<% end %>
				<%= link_to edit_user_registration_path  do%>
					<li>Edit Profile</li>
				<% end %>
				<%= link_to search_path do%>
					<li>Search</li>
				<% end %>
			</ul>
			<ul>
				<li class="listHeader">Your Posts</li>
					<%= link_to dashboard_path + '/all' do %>
						<li>All Posts</li>
					<% end %>
				<%= link_to dashboard_path + '/open' do %>
					<li>Open Posts</li>
				<% end %>
				<%= link_to dashboard_path + '/completed' do %>
					<li>Completed Posts</li>
				<% end %>
			</ul>
			<ul>
				<li class="listHeader">Notifications</li>
				<a href="#"><li>Request for Contact Info</li></a>
				<a href="#"><li>Review Required</li></a>
				<a href="#"><li><i>View more ></i></li></a>
			</ul>
		</div>
	</div>
</div>
<footer><h5>&#169; Copyright Karmik 2014. All Rights Reserved.</h5></footer>
</body>
</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Karmik</title>
		<%= stylesheet_link_tag 'landing.css' %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  	<%= csrf_meta_tags %>
		<link href='http://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700,300italic' rel='stylesheet' type='text/css'>
	</head>
	<body>
		<section class="heroWrapper" data-type="background">
			<div class="navbar">
				<%= image_tag 'karmic-logo.svg', class: 'logo' %>
				<div class="navLinks">
					<%= link_to  new_user_registration_path, class: 'navLink' do %>
						<div>Sign Up</div>
					<% end %>
					<%= link_to new_user_session_path, class: 'navLink' do %>
						<div>Log In</div>
					<% end %>
				</div>
			</div>
			<div class="hero">
				<h1>Share your skills and give<br>back to your community.</h1>
				<a href="#"><div class="heroSign">Sign Up for a Free Account</div></a><div class="heroMore">or&nbsp;&nbsp;&nbsp;&nbsp;<a href="#myAnchor" class="anchorLink" href="#myAnchor" rel="" id="anchor1">Learn More ></a></div>
			</div>
		</section>
		<div class="contentWrapper orange small" name="myAnchor" id="myAnchor">
			<div class="contentBox landingBox">
				<p>This is Karmik, an online community where you can help others and give back to your local community.</p>
			</div>
		</div>
		<div class="contentWrapper">
			<div class="contentBox landingBox">
				<h1>Here's how it works:</h1>
				<%= image_tag 'howitworks.png'%>
			</div>
		</div>
		<footer><h5>&#169; Copyright Karmik 2014. All Rights Reserved.</h5></footer>
		<script type="text/javascript">
			$( document ).ready(function() {
				$('a').click(function(){
				    $('html, body').animate({
				        scrollTop: $( $(this).attr('href') ).offset().top
				    }, 500);
				    return false;
				});
			});
		</script>
	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Orange</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!--
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
-->
<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Karmik</title>
  </head>
  <body>
    <%= form_for(@post) do |f| %>
    <div class="modal">
    <div class="modalBox">
        <div class="boxHead">
          <%= image_tag 'karmic-logo.svg', class: 'logo' %>
        </div>
        <div class="boxBody">
          <label><%= f.label :title %></label>
          <%= f.text_field :title %>
          <label><%= f.label :description %></label>
          <%= f.text_field :description %>
          <label><%= f.label :give %></label>
           <%= f.select :give, options_for_select([['Give', true], ['Take', false]]) %>
          <%= f.submit "Edit Post", class: "addButton" %>
        </div>
    </div>
    </div>
  <% end %>
  </body>
</html>

app/views/posts/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Karmik</title>
  </head>
  <body>
    <%= form_for(@post) do |f| %>
    <div class="modal">
    <div class="modalBox">
        <div class="boxHead">
          <%= image_tag 'karmic-logo.svg', class: 'logo' %>
        </div>
        <div class="boxBody">
          <label><%= f.label :title %></label>
          <%= f.text_field :title %>
          <label><%= f.label :description %></label>
          <%= f.text_field :description %>
          <label><%= f.label :give %></label>
           <%= f.select :give, options_for_select([['Give', true], ['Take', false]]) %>
          <%= f.submit "Add Post", class: "addButton" %>
        </div>
    </div>
    </div>
  <% end %>
  </body>
</html>

app/views/posts/show.html.erb
<script>
document.location = "<%= dashboard_path %>"
</script>

app/views/profiles/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Karmik</title>
	<%= stylesheet_link_tag 'profile.css' %>
	<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"/>
	<link href='http://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700,300italic' rel='stylesheet' type='text/css'>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="headerWrapper">
		<div class="header">
			<%= link_to dashboard_path do %>
			<%= image_tag 'karmic-logo.svg', class: 'logo' %>
			<% end %>
			<div class="navLinks">
				<%= link_to search_path, class: 'navLink' do%>
				<div>Search</div>
				<% end %>
				<%= link_to profile_path(current_user), class: 'navLink' do %>
				<div><%= current_user.name %></div>
				<% end %>
				<% if user_signed_in? %>
				<%= link_to destroy_user_session_path, method: :delete, class: 'navLink' do %>
				<div>Sign Out</div>
				<% end %>
				<% end %>
			</div>
		</div>
	</div>
	<div class="heroWrapper">
		<div class="hero">
			<div class="userHero">
				<img src=<%= get_gravatar(@user)%> class="pictureHero"/>
				<div class="namePlaceHero">
					<h2 class="nameHero"><%= @user.name %></h2>
					<h2 class="placeHero"><% unless @user.city.nil? %>
						<%= @user.city %>
						<% end %>
						<% unless @user.state.nil? %>,
						<%= @user.state %>
						<% end %></h2>
					</div>
				</div>
				<div class="statHero">
					<div class="gameHero">
						<%= image_tag 'badges.jpg' %>
					</div>
					<div class="ratioHero">
						<div class="giveBox"><h1>28</h1><p>TIMES GIVEN</p></div>
						<div class="receiveBox"><h1>21</h1><p>TIMES RECEIVED</p></div>
					</div>
				</div>
			</div>
		</div>
		<div class="dashboardWrapper">
			<div class="feedWrapper">
				<div class="feedBox">
					<h3>About Me</h3>
					<p><%= @user.description %></p>
					<!--<p>Laborum organic 90's McSweeney's elit dolore. Ethnic cray Banksy kitsch Brooklyn 90's blog trust fund. Neutra 3 wolf moon XOXO esse, ethnic church-key Pitchfork dolore fixie tempor nihil Portland tousled. Cupidatat commodo occupy, artisan readymade VHS typewriter next level raw denim skateboard aliquip blog biodiesel fugiat fashion axe. Wolf duis freegan bespoke fashion axe. Brunch art party beard pickled chillwave. Quis id sapiente cred velit laboris.</p>-->
					<h3>Skills and Interests</h3>
					<p class="orange">Babysitting, Teaching, Programming</p>
					<h3>Reviews</h3>
					<% if @reviews.empty? %>
						<h2 class="feedHead"><i>No reviews yet. :'( </i></h2>
					<% else %>
						<h2 class="feedHead">Recent Posts in Your Community</h2>
						<% @reviews.each do |review| %>
							<div class="reviewBox">
								<div class="reviewLeft">
									<img src=<%= get_gravatar(review.user)%> class="reviewPicture"/>
									<div class="reviewRating"><i class="fa fa-smile-o"></i></div>
									<p class="reviewName"><b><%= review.title %></b></p>
									<p class="reviewPlace">San Luis Obispo, CA</p>
								</div>
								<div class="reviewRight">
									<%= review.feedback %>
								</div>
							</div>
							<hr>
						<% end %>
					<% end %>
					<!--<div class="reviewBox">
						<div class="reviewLeft">
							<img src=<%= get_gravatar(@user)%> class="reviewPicture"/>
							<div class="reviewRating"><i class="fa fa-smile-o"></i></div>
							<p class="reviewName"><b><%= @user.name %></b></p>
							<p class="reviewPlace">San Luis Obispo, CA</p>
						</div>
						<div class="reviewRight">
							<p>Lorraine was great. She tutored my kids and acted as a babysitter for them. She is a model professor and human being. Hopefully she will be available again in the future.</p>
						</div>
					</div>-->
				</div><!-- close feedwrapper -->
			</div><!-- close feedbox -->
			<div class="sidebarWrapper">
				<div class="sidebar">
					<div class="postFeed">
						<h2 class="feedHead">Open Posts</h2>
						<% if @posts.empty? %>
						<h2 class="feedHead"><i>No posts found. :'( </i></h2>
						<% else %>
						<% @posts.each do |post| %>
						<div class="post <%= post.created_by==post.user ? 'takePost' : 'givePost' %>">
							<div class="feedTextBox">
								<h3 class="postTitle"><%= post.title %></h3>
								<p><%= post.description %></p>
								<div class="postButton">Connect</div>
							</div>
						</div>
						<% end %>
						<% end %>
						<a href=""><div class="shoveToRight orange">View All ></div></a>
					</div>
				</div>
			</div>
		</div>
		<footer><h5>&#169; Copyright Karmik 2014. All Rights Reserved.</h5></footer>
		<div class="achBox" style="display: none;">
			<div class="acheivement">
				<%= image_tag 'break-the-ice.png', class: 'achBadge' %>
				<div class="achBody">
					<h2>Achievement Unlocked</h2>
					<h1>Break the Ice</h1>
				</div>
			</div>
		</div>
		<script type="text/javascript">
		$( document ).ready(function() {
			$('.postButton').click(function(){
				$(this).html('Sent!');
				$('.achBox').slideDown(1000);
				$('.achBox').delay(5000).slideUp(1000);
			});
		});
		</script>
	</body>
	</html>

	<!--<h1>Profile</h1>
	<br>
	<h2>About</h2>

	<%= @user.name %>
	<br>
	<%= @user.email %>
	<br>

	<% unless @user.city.nil? %>
	<%= @user.city %> <br>
	<% end %>
	<% unless @user.state.nil? %>
	<%= @user.state %> <br>
	<% end %>
	<br>
	<% unless @user.website.nil? %>
	<%= @user.website %> <br>
	<% end %>

	<% unless @user.twitter.nil? %>
	<%= @user.twitter %> <br>
	<% end %>

	<% unless @user.facebook.nil? %>
	<%= @user.facebook %> <br>
	<% end %>
	<% unless @user.phone.nil? %>
	<%= @user.phone %> <br>
	<% end %>
	<br>
	<h2>Needs</h2>
	<br>
	<h2>Service</h2>
	<br>
	<h2>Reviews</h2>
	<% unless @user.updated_at.nil? %>
	<%= @user.updated_at %> <br>
	<% end %>

	<% unless @user.role.nil? %>
	<%= @user.role%> <br>
	<% end %>
	<% @user.reviews.each do |review| %>
	<%= review.feedback %>
	<% end %>-->

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/search/index.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Karmik</title>
		<%= stylesheet_link_tag 'search.css' %>
		<link rel="stylesheet" type="text/css" href="search.css"/>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  	<%= csrf_meta_tags %>
		<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"/>
		<link href='http://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700,300italic' rel='stylesheet' type='text/css'>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	</head>
	<body>
		<div class="headerWrapper">
			<div class="header">
				<%= link_to dashboard_path do %>
				<%= image_tag 'karmic-logo.svg', class: 'logo' %>
				<% end %>
				<div class="navLinks">
					<%= link_to search_path, class: 'navLink' do%>
						<div>Search</div>
					<% end %>
					<%= link_to profile_path(current_user), class: 'navLink' do %>
             <div><%= current_user.name %></div>
          <% end %>
          <% if user_signed_in? %>
						<%= link_to destroy_user_session_path, method: :delete, class: 'navLink' do %>
							<div>Sign Out</div>
						<% end %>
					<% end %>
				</div>
			</div>
		</div>
		<form>
		<div class="heroWrapper">
			<div class="hero">
				<h1>Search</h1>
				<%= form_tag do %>
					<div class="heroSelect">
						<select>
						    <option value="need">I Need</option>
						    <option value="give">I Can Give</option>
						</select>
						<div class="dropArrow">
							<i class="fa fa-caret-down"></i>
						</div>
					</div>
					<input type="text" placeholder="Search" name='query' value='<%= params[:query] %>' class="searchBox"/>
					<input type="submit" class="searchButton" name='submit' value="Get Results"/>
				<% end %>

			</div>
		</div>
		<div class="dashboardWrapper">
			<div class="feedWrapper">
				<div class="feedBox">
					<div class="postFeed">
						<h2 class="feedHead">
							<% if params[:query] %>
								<%= @results.count unless @results.nil? %> Results for <b><%= params[:query] %></b> in <b>San Luis Obispo, CA</b></h2>
							<% else %>
								All Posts</h2>
							<% end %>

						<% @results.each do |result| %>
							<div class="post <%= result.created_by==result.user ? 'takePost' : 'givePost' %>">
								<img src="<%= get_gravatar(result.created_by,110) %>" class="feedProfilePic"/>
								<div class="feedTextBox">
									<h3 class="postTitle"><%= result.title %></h3>
									<p><%= result.description %></p>
									<%= link_to post_path result do %>
										<%= link_to post_connect_path result do %><div class="postButton">Connect</div><% end %><%= link_to profile_path(result.created_by) do %><div class="viewButton">View Profile</div><% end %>
									<% end %>
								</div>
							</div>
						<% end %>


					</div>
				</div>
			</div>
			<div class="sidebarWrapper">
				<div class="sidebar">
					<h1>Filter Results</h1>
					<ul>
						<li><input type="checkbox" class="searchCheckbox" id="option1"/> <label for="option1">Date</label></li>
						<li><input type="checkbox" class="searchCheckbox" id="option2"/> <label for="option1">Rating</label></li>
						<li><input type="checkbox" class="searchCheckbox" id="option3"/> <label for="option1">Ratio</label></li>
						<li><i>Can't find what you're looking for? <%= link_to "Create a new Post >", new_post_path %></i></li>
					</ul>
				</div>
			</div>
		</div>
		</form>
		<footer><h5>&#169; Copyright Karmik 2014. All Rights Reserved.</h5></footer>
	</body>
</html>